spec:
  resources:
    limits:
      cpu: "100m" 
      memory: "1Gi"
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "50m"
              memory: 256Mi
            limits:
              cpu: "250m"
              memory: 456Mi
            livenessProbe:
              initialDelaySeconds: 60
              tcpSocket:
                port: 8080
            readinessProbe:
              initialDelaySeconds: 60
              tcpSocket:
                port: 8080
          env:
          - name: CONFIG_LOCATION
            value: /data
          - name: SPRING_CONFIG_LOCATION
            value: /data/application.properties
          - name: TZ
            value: America/Bogota
          volumeMounts:
            - mountPath: /data
              name: volume-paginator
      volumes:
        - configMap:
            defaultMode: 420
            name: paginator-config
          name: volume-paginator